# -*- coding: utf-8 -*-

from PyQt5 import QtCore,QtWidgets

class Ui_CarControl(object):
    def __init__(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.setupUi(self.MainWindow)

    def setupUi(self, UI_carControl):
        UI_carControl.setObjectName("UI_carControl")
        UI_carControl.resize(1041, 605)
        self.label_text1 = QtWidgets.QLabel(UI_carControl)
        self.label_text1.setGeometry(QtCore.QRect(0, 50, 361, 111))
        self.label_text1.setStyleSheet("font: 34pt \"宋体\";\n"
                                       "color: rgb(255, 255, 255);")
        self.label_text1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text1.setObjectName("label_text1")
        self.label_text2 = QtWidgets.QLabel(UI_carControl)
        self.label_text2.setGeometry(QtCore.QRect(110, 150, 101, 51))
        self.label_text2.setStyleSheet("font: 14pt \"宋体\";\n"
                                       "color: rgb(255, 255, 255);")
        self.label_text2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text2.setObjectName("label_text2")
        self.label_icon1 = QtWidgets.QLabel(UI_carControl)
        self.label_icon1.setGeometry(QtCore.QRect(120, 200, 72, 41))
        self.label_icon1.setObjectName("label_icon1")
        self.frame = QtWidgets.QFrame(UI_carControl)
        self.frame.setGeometry(QtCore.QRect(70, 250, 191, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 160, 153))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_1_f_h = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_1_f_h.setObjectName("radioButton_1_f_h")
        self.verticalLayout.addWidget(self.radioButton_1_f_h)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.radioButton_1_f_l = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_1_f_l.setObjectName("radioButton_1_f_l")
        self.verticalLayout.addWidget(self.radioButton_1_f_l)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.radioButton_1_b_h = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_1_b_h.setObjectName("radioButton_1_b_h")
        self.verticalLayout.addWidget(self.radioButton_1_b_h)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.radioButton_1_b_l = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_1_b_l.setObjectName("radioButton_1_b_l")
        self.verticalLayout.addWidget(self.radioButton_1_b_l)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.radioButton_1_s = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_1_s.setObjectName("radioButton_1_s")
        self.verticalLayout.addWidget(self.radioButton_1_s)
        self.label_text3 = QtWidgets.QLabel(UI_carControl)
        self.label_text3.setGeometry(QtCore.QRect(330, 150, 101, 51))
        self.label_text3.setStyleSheet("font: 14pt \"宋体\";\n"
                                       "color: rgb(255, 255, 255);")
        self.label_text3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text3.setObjectName("label_text3")
        self.label_icon2 = QtWidgets.QLabel(UI_carControl)
        self.label_icon2.setGeometry(QtCore.QRect(340, 200, 72, 41))
        self.label_icon2.setObjectName("label_icon2")
        self.label_text4 = QtWidgets.QLabel(UI_carControl)
        self.label_text4.setGeometry(QtCore.QRect(550, 150, 101, 51))
        self.label_text4.setStyleSheet("font: 14pt \"宋体\";\n"
                                       "color: rgb(255, 255, 255);")
        self.label_text4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text4.setObjectName("label_text4")
        self.label_icon3 = QtWidgets.QLabel(UI_carControl)
        self.label_icon3.setGeometry(QtCore.QRect(560, 200, 72, 41))
        self.label_icon3.setObjectName("label_icon3")
        self.frame_2 = QtWidgets.QFrame(UI_carControl)
        self.frame_2.setGeometry(QtCore.QRect(290, 250, 191, 231))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 160, 153))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_2_f_h = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2_f_h.setObjectName("radioButton_2_f_h")
        self.verticalLayout_2.addWidget(self.radioButton_2_f_h)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.radioButton_2_f_l = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2_f_l.setObjectName("radioButton_2_f_l")
        self.verticalLayout_2.addWidget(self.radioButton_2_f_l)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.radioButton_2_b_h = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2_b_h.setObjectName("radioButton_2_b_h")
        self.verticalLayout_2.addWidget(self.radioButton_2_b_h)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.radioButton_2_b_l = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2_b_l.setObjectName("radioButton_2_b_l")
        self.verticalLayout_2.addWidget(self.radioButton_2_b_l)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.radioButton_2_s = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2_s.setObjectName("radioButton_2_s")
        self.verticalLayout_2.addWidget(self.radioButton_2_s)
        self.frame_3 = QtWidgets.QFrame(UI_carControl)
        self.frame_3.setGeometry(QtCore.QRect(520, 250, 191, 231))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 40, 160, 153))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_3_f_h = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_3_f_h.setObjectName("radioButton_3_f_h")
        self.verticalLayout_3.addWidget(self.radioButton_3_f_h)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.radioButton_3_f_l = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_3_f_l.setObjectName("radioButton_3_f_l")
        self.verticalLayout_3.addWidget(self.radioButton_3_f_l)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.radioButton_3_b_h = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_3_b_h.setObjectName("radioButton_3_b_h")
        self.verticalLayout_3.addWidget(self.radioButton_3_b_h)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem10)
        self.radioButton_3_b_l = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_3_b_l.setObjectName("radioButton_3_b_l")
        self.verticalLayout_3.addWidget(self.radioButton_3_b_l)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem11)
        self.radioButton_3_s = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_3_s.setObjectName("radioButton_3_s")
        self.verticalLayout_3.addWidget(self.radioButton_3_s)

        self.retranslateUi(UI_carControl)
        QtCore.QMetaObject.connectSlotsByName(UI_carControl)

    def retranslateUi(self, UI_carControl):
        _translate = QtCore.QCoreApplication.translate
        UI_carControl.setWindowTitle(_translate("UI_carControl", "Dialog"))
        self.label_text1.setText(_translate("UI_carControl", "车辆管理系统"))
        self.label_text2.setText(_translate("UI_carControl", "1.救护车"))
        self.label_icon1.setText(_translate("UI_carControl", "icon1"))
        self.radioButton_1_f_h.setText(_translate("UI_carControl", "  前进高速"))
        self.radioButton_1_f_l.setText(_translate("UI_carControl", "  前进低速"))
        self.radioButton_1_b_h.setText(_translate("UI_carControl", "  后退高速"))
        self.radioButton_1_b_l.setText(_translate("UI_carControl", "  后退低速"))
        self.radioButton_1_s.setText(_translate("UI_carControl", "    停车"))
        self.label_text3.setText(_translate("UI_carControl", "2.大巴车"))
        self.label_icon2.setText(_translate("UI_carControl", "icon2"))
        self.label_text4.setText(_translate("UI_carControl", "3.消防车"))
        self.label_icon3.setText(_translate("UI_carControl", "icon3"))
        self.radioButton_2_f_h.setText(_translate("UI_carControl", "  前进高速"))
        self.radioButton_2_f_l.setText(_translate("UI_carControl", "  前进低速"))
        self.radioButton_2_b_h.setText(_translate("UI_carControl", "  后退高速"))
        self.radioButton_2_b_l.setText(_translate("UI_carControl", "  后退低速"))
        self.radioButton_2_s.setText(_translate("UI_carControl", "    停车"))
        self.radioButton_3_f_h.setText(_translate("UI_carControl", "  前进高速"))
        self.radioButton_3_f_l.setText(_translate("UI_carControl", "  前进低速"))
        self.radioButton_3_b_h.setText(_translate("UI_carControl", "  后退高速"))
        self.radioButton_3_b_l.setText(_translate("UI_carControl", "  后退低速"))
        self.radioButton_3_s.setText(_translate("UI_carControl", "    停车"))

