# -*- coding: utf-8 -*-

from PyQt5 import QtCore,QtWidgets

class Ui_CarView(object):
    def __init__(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.setupUi(self.MainWindow)

    def setupUi(self, UI_carView):
        UI_carView.setObjectName("UI_carView")
        UI_carView.resize(1041, 605)
        self.label_text1 = QtWidgets.QLabel(UI_carView)
        self.label_text1.setGeometry(QtCore.QRect(20, 50, 361, 111))
        self.label_text1.setStyleSheet("font: 34pt \"宋体\";\n"
                                       "color: rgb(255, 255, 255);")
        self.label_text1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text1.setObjectName("label_text1")
        self.label_text2 = QtWidgets.QLabel(UI_carView)
        self.label_text2.setGeometry(QtCore.QRect(30, 150, 361, 111))
        self.label_text2.setStyleSheet("font: 20pt \"宋体\";\n"
                                       "color: rgb(255, 255, 255);")
        self.label_text2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_text2.setObjectName("label_text2")
        self.toolButton_carMore = QtWidgets.QToolButton(UI_carView)
        self.toolButton_carMore.setGeometry(QtCore.QRect(210, 400, 91, 31))
        self.toolButton_carMore.setObjectName("toolButton_carMore")
        self.horizontalLayoutWidget = QtWidgets.QWidget(UI_carView)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 300, 195, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_carA = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_carA.setObjectName("pushButton_carA")
        self.horizontalLayout.addWidget(self.pushButton_carA)
        self.pushButton_carB = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_carB.setObjectName("pushButton_carB")
        self.horizontalLayout.addWidget(self.pushButton_carB)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(UI_carView)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 350, 195, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_carC = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_carC.setObjectName("pushButton_carC")
        self.horizontalLayout_2.addWidget(self.pushButton_carC)
        self.pushButton_carFire = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_carFire.setObjectName("pushButton_carFire")
        self.horizontalLayout_2.addWidget(self.pushButton_carFire)
        self.pushButton_carAmbul = QtWidgets.QPushButton(UI_carView)
        self.pushButton_carAmbul.setGeometry(QtCore.QRect(110, 400, 93, 31))
        self.pushButton_carAmbul.setObjectName("pushButton_carAmbul")
        self.label_background = QtWidgets.QLabel(UI_carView)
        self.label_background.setGeometry(QtCore.QRect(470, 190, 491, 391))
        self.label_background.setText("")
        self.label_background.setObjectName("label_background")
        self.pushButton_start = QtWidgets.QPushButton(UI_carView)
        self.pushButton_start.setGeometry(QtCore.QRect(720, 140, 93, 28))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(UI_carView)
        self.pushButton_stop.setGeometry(QtCore.QRect(830, 140, 93, 28))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_carAll = QtWidgets.QPushButton(UI_carView)
        self.pushButton_carAll.setGeometry(QtCore.QRect(210, 450, 93, 28))
        self.pushButton_carAll.setObjectName("pushButton_carAll")

        self.retranslateUi(UI_carView)
        QtCore.QMetaObject.connectSlotsByName(UI_carView)

    def retranslateUi(self, UI_carView):
        _translate = QtCore.QCoreApplication.translate
        UI_carView.setWindowTitle(_translate("UI_carView", "Dialog"))
        self.label_text1.setText(_translate("UI_carView", "设施管理系统"))
        self.label_text2.setText(_translate("UI_carView", "显示车辆"))
        self.toolButton_carMore.setText(_translate("UI_carView", "..."))
        self.pushButton_carA.setText(_translate("UI_carView", "车辆A"))
        self.pushButton_carB.setText(_translate("UI_carView", "车辆B"))
        self.pushButton_carC.setText(_translate("UI_carView", "车辆C"))
        self.pushButton_carFire.setText(_translate("UI_carView", "消防车"))
        self.pushButton_carAmbul.setText(_translate("UI_carView", "救护车"))
        self.pushButton_start.setText(_translate("UI_carView", "接收"))
        self.pushButton_stop.setText(_translate("UI_carView", "停止"))
        self.pushButton_carAll.setText(_translate("UI_carView", "全部车辆"))

